apiVersion: v1
kind: Service
metadata:
  name: {{ include "purser.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "purser.name" . }}
    helm.sh/chart: {{ include "purser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "purser.name" . }}-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
